version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '9898:9898'
    volumes:
      - ./:/app
      - /app/node_modules
      # SSL for Express
      - ./certs:/certs
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  redis:
    image: redis:latest
    container_name: redis
    restart: 'unless-stopped'
    ports:
      - '6378:6379'
    networks:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27016:27017'
    volumes:
      # Location for MongoDB data
      - ./mongo/data:/data/db
    networks:
      - backend
    command: --bind_ip_all --replSet loa

networks:
  backend:

volumes:
  data:
    driver: local
