version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '9898:9898'
    volumes:
      - ./:/app
      - /app/node_modules
      # SSL for Express
      - ./certs:/certs
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:

volumes:
  data:
    driver: local
