const LostarkClass = {
  DESTROYER: 103,
  UNRELEASED: 1,
  ARCANA: 202,
  BERSERKER: 102,
  WARDANCER: 302,
  DEADEYE: 503,
  UNRELEASED0: 6,
  GUNLANCER: 104,
  GUNNER: 8,
  SCRAPPER: 303,
  MAGE: 10,
  SUMMONER: 203,
  WARRIOR: 12,
  SOULFIST: 304,
  SHARPSHOOTER: 502,
  ARTILLERIST: 504,
  BARD: 204,
  GLAIVIER: 305,
  ASSASSIN: 18,
  DEATHBLADE: 402,
  SHADOWHUNTER: 403,
  PALADIN: 105,
  SCOUTER: 505,
  UNRELEASED3: 23,
  UNRELEASED4: 24,
  GUNSLINGER: 512,
  UNRELEASED5: 26,
  STRIKER: 312,
  SORCERESS: 205,
  REAPER: 404,
};

const Classes = [
  { id: LostarkClass.DESTROYER, name: "Destroyer" },
  { id: LostarkClass.UNRELEASED, name: "Unreleased" },
  { id: LostarkClass.ARCANA, name: "Arcana" },
  { id: LostarkClass.BERSERKER, name: "Berserker" },
  { id: LostarkClass.WARDANCER, name: "Wardancer" },
  { id: LostarkClass.DEADEYE, name: "Deadeye" },
  { id: LostarkClass.UNRELEASED0, name: "Unreleased" },
  { id: LostarkClass.GUNLANCER, name: "Gunlancer" },
  { id: LostarkClass.GUNNER, name: "Gunner" },
  { id: LostarkClass.SCRAPPER, name: "Scrapper" },
  { id: LostarkClass.MAGE, name: "Mage" },
  { id: LostarkClass.SUMMONER, name: "Summoner" },
  { id: LostarkClass.WARRIOR, name: "Warrior" },
  { id: LostarkClass.SOULFIST, name: "Soulfist" },
  { id: LostarkClass.SHARPSHOOTER, name: "Sharpshooter" },
  { id: LostarkClass.ARTILLERIST, name: "Artillerist" },
  { id: LostarkClass.BARD, name: "Bard" },
  { id: LostarkClass.GLAIVIER, name: "Glaivier" },
  { id: LostarkClass.ASSASSIN, name: "Assassin" },
  { id: LostarkClass.DEATHBLADE, name: "Deathblade" },
  { id: LostarkClass.SHADOWHUNTER, name: "Shadowhunter" },
  { id: LostarkClass.PALADIN, name: "Paladin" },
  { id: LostarkClass.SCOUTER, name: "Scouter" },
  { id: LostarkClass.UNRELEASED3, name: "Unreleased" },
  { id: LostarkClass.UNRELEASED4, name: "Unreleased" },
  { id: LostarkClass.GUNSLINGER, name: "Gunslinger" },
  { id: LostarkClass.UNRELEASED5, name: "Unreleased" },
  { id: LostarkClass.STRIKER, name: "Striker" },
  { id: LostarkClass.SORCERESS, name: "Sorceress" },
];

export { LostarkClass, Classes };
