const LostarkClass = {
  DESTROYER: 0,
  UNRELEASED: 1,
  ARCANA: 2,
  BERSERKER: 3,
  WARDANCER: 4,
  DEADEYE: 5,
  UNRELEASED0: 6,
  GUNLANCER: 7,
  GUNNER: 8,
  SCRAPPER: 9,
  MAGE: 10,
  UNRELEASED1: 11,
  WARRIOR: 12,
  SOULFIST: 13,
  SHARPSHOOTER: 14,
  ARTILLERIST: 15,
  BARD: 16,
  GLAIVIER: 17,
  ASSASSIN: 18,
  DEATHBLADE: 19,
  SHADOWHUNTER: 20,
  PALADIN: 21,
  SCOUTER: 22,
  UNRELEASED3: 23,
  UNRELEASED4: 24,
  GUNSLINGER: 25,
  UNRELEASED5: 26,
  STRIKER: 27,
  SORCERESS: 28,
};

const Classes = [
  { id: LostarkClass.DESTROYER, name: 'Destroyer' },
  { id: LostarkClass.UNRELEASED, name: 'Unreleased' },
  { id: LostarkClass.ARCANA, name: 'Arcana' },
  { id: LostarkClass.BERSERKER, name: 'Berserker' },
  { id: LostarkClass.WARDANCER, name: 'Wardancer' },
  { id: LostarkClass.DEADEYE, name: 'Deadeye' },
  { id: LostarkClass.UNRELEASED0, name: 'Unreleased' },
  { id: LostarkClass.GUNLANCER, name: 'Gunlancer' },
  { id: LostarkClass.GUNNER, name: 'Gunner' },
  { id: LostarkClass.SCRAPPER, name: 'Scrapper' },
  { id: LostarkClass.MAGE, name: 'Mage' },
  { id: LostarkClass.UNRELEASED1, name: 'Unreleased' },
  { id: LostarkClass.WARRIOR, name: 'Warrior' },
  { id: LostarkClass.SOULFIST, name: 'Soulfist' },
  { id: LostarkClass.SHARPSHOOTER, name: 'Sharpshooter' },
  { id: LostarkClass.ARTILLERIST, name: 'Artillerist' },
  { id: LostarkClass.BARD, name: 'Bard' },
  { id: LostarkClass.GLAIVIER, name: 'Glaivier' },
  { id: LostarkClass.ASSASSIN, name: 'Assassin' },
  { id: LostarkClass.DEATHBLADE, name: 'Deathblade' },
  { id: LostarkClass.SHADOWHUNTER, name: 'Shadowhunter' },
  { id: LostarkClass.PALADIN, name: 'Paladin' },
  { id: LostarkClass.SCOUTER, name: 'Scouter' },
  { id: LostarkClass.UNRELEASED3, name: 'Unreleased' },
  { id: LostarkClass.UNRELEASED4, name: 'Unreleased' },
  { id: LostarkClass.GUNSLINGER, name: 'Gunslinger' },
  { id: LostarkClass.UNRELEASED5, name: 'Unreleased' },
  { id: LostarkClass.STRIKER, name: 'Striker' },
  { id: LostarkClass.SORCERESS, name: 'Sorceress' },
];

export { LostarkClass, Classes };
